This might properly detect and workaround the LPR0 bug.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2706,7 +2706,7 @@ echo "${ECHO_T}no" >&6
 
      case "${host_cpu}" in
         i?86)
-           opt="-mcpu=${host_cpu} -march=i386"
+           opt="-mcpu=${host_cpu}"
 
  opt="$opt"
  echo "$as_me:2712: checking if $CXX accepts $opt" >&5
@@ -6028,6 +6028,21 @@ else
   SHARED_NO=''
 fi
 
+# Work around broken compilers with the famous LPR0 bug
+if test x$ac_shared_libdjvu != xno && test x$GXX = xyes; then
+    echo "$as_me:6033: checking if $CXX has the LPR0 bug" >&5
+echo $ECHO_N "checking if $CXX has the LPR0 bug... $ECHO_C" >&6
+    echo 'extern "C" { inline int sqr(int x) throw() { return x * x ; } } int main() {} ' > conftest.cc
+    if ${CXX} -fPIC ${OPTS} conftest.cc -o conftest >/dev/null 2>/dev/null ; then
+        echo "$as_me:6037: result: no" >&5
+echo "${ECHO_T}no" >&6
+    else
+        echo "$as_me:6040: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        OPTS=`echo $OPTS | sed -e 's/-mcpu=i686/-mpentium/'`
+    fi
+fi
+
 # ----------------------------------------
 # End
 # ----------------------------------------
@@ -6171,7 +6186,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6174: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6189: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -6344,7 +6359,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:6347: error: ambiguous option: $1
+    { { echo "$as_me:6362: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6363,7 +6378,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:6366: error: unrecognized option: $1
+  -*) { { echo "$as_me:6381: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6406,7 +6421,7 @@ do
   "gui/djview/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/djview/Makefile" ;;
   "gui/nsdejavu/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/nsdejavu/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config/config.h.in" ;;
-  *) { { echo "$as_me:6409: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:6424: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -6655,7 +6670,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:6658: creating $ac_file" >&5
+    { echo "$as_me:6673: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -6673,7 +6688,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6676: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6691: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6686,7 +6701,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6689: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6704: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6747,7 +6762,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6750: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6765: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6758,7 +6773,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6761: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6776: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6771,7 +6786,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6774: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6789: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6888,7 +6903,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6891: $ac_file is unchanged" >&5
+      { echo "$as_me:6906: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
