Added autoconf test for intel atomic builtins. Fixed gnuc version test in atomic.cpp.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21666,6 +21666,77 @@ _ACEOF
 
 fi
 
+{ echo "$as_me:$LINENO: checking whether the compiler supports intel atomic builtins" >&5
+echo $ECHO_N "checking whether the compiler supports intel atomic builtins... $ECHO_C" >&6; }
+if test "${ac_cv_cxx_intel_atomic_builtins+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+ ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+static int volatile l;
+int
+main ()
+{
+__sync_lock_test_and_set(&l,1); return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_cxx_intel_atomic_builtins=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_cxx_intel_atomic_builtins=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_cxx_intel_atomic_builtins" >&5
+echo "${ECHO_T}$ac_cv_cxx_intel_atomic_builtins" >&6; }
+if test "$ac_cv_cxx_intel_atomic_builtins" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_INTEL_ATOMIC_BUILTINS 1
+_ACEOF
+
+fi
+
  CXXRPOFLAGS=
   RPO_YES='#'
   RPO_NO=''
