Attempt to make warning messages more prominent and to better detect failues to locate MOC.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6222,11 +6222,15 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-    test -x "$MOC" || QTDIR=no
+    if ! test -x "$MOC" ; then
+        { echo "$as_me:6226: WARNING: Cannot run the Qt Meta-Object compiler." >&5
+echo "$as_me: WARNING: Cannot run the Qt Meta-Object compiler." >&2;}
+        QTDIR=no
+    fi
   fi
   # Execute
   if test x$QTDIR != xno ; then
-    echo "$as_me:6229: checking if a small Qt program runs" >&5
+    echo "$as_me:6233: checking if a small Qt program runs" >&5
 echo $ECHO_N "checking if a small Qt program runs... $ECHO_C" >&6
     ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -6239,12 +6243,12 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
     CXXFLAGS="$CXXFLAGS $CFLAGS $QT_CFLAGS $X_CFLAGS"
     LIBS="$QT_LIBS $X_LIBS $LIBS"
     if test "$cross_compiling" = yes; then
-  { { echo "$as_me:6242: error: cannot run test program while cross compiling" >&5
+  { { echo "$as_me:6246: error: cannot run test program while cross compiling" >&5
 echo "$as_me: error: cannot run test program while cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 6247 "configure"
+#line 6251 "configure"
 #include "confdefs.h"
 
 #include <qfile.h>
@@ -6256,15 +6260,15 @@ QTextStream ts(&qf); ts << QT_VERSION; return 0;
 }
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:6259: \"$ac_link\"") >&5
+if { (eval echo "$as_me:6263: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:6262: \$? = $ac_status" >&5
+  echo "$as_me:6266: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:6264: \"$ac_try\"") >&5
+  { (eval echo "$as_me:6268: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:6267: \$? = $ac_status" >&5
+  echo "$as_me:6271: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   okay=yes
 else
@@ -6283,15 +6287,15 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-    echo "$as_me:6286: result: $okay" >&5
+    echo "$as_me:6290: result: $okay" >&5
 echo "${ECHO_T}$okay" >&6
   fi
   # Version
   if test x$QTDIR != xno ; then
-     echo "$as_me:6291: checking Qt version" >&5
+     echo "$as_me:6295: checking Qt version" >&5
 echo $ECHO_N "checking Qt version... $ECHO_C" >&6
      qt_version=`cat < confout`
-     echo "$as_me:6294: result: $qt_version" >&5
+     echo "$as_me:6298: result: $qt_version" >&5
 echo "${ECHO_T}$qt_version" >&6
 
 cat >>confdefs.h <<EOF
@@ -6302,9 +6306,9 @@ EOF
   fi
   # Execute
   if test x$QTDIR = xno ; then
-    QT_CFLAGS= ; QT_LIBS= ; QTDIR=
+    QT_CFLAGS= ; QT_LIBS= ; QTDIR= ; MOC=moc ;
      no_qt=yes
-  { echo "$as_me:6307: WARNING: Qt support is disabled" >&5
+  { echo "$as_me:6311: WARNING: Qt support is disabled" >&5
 echo "$as_me: WARNING: Qt support is disabled" >&2;}
   else
     :
@@ -6324,7 +6328,7 @@ else
 fi;
 if test x$no_threads = xyes ||
    test x$no_qt = xyes ; then
-   { echo "$as_me:6327: WARNING: Disabling compilation of djview" >&5
+   { echo "$as_me:6331: WARNING: Disabling compilation of djview" >&5
 echo "$as_me: WARNING: Disabling compilation of djview" >&2;}
    GUI_YES='#'
    GUI_NO=''
@@ -6336,53 +6340,6 @@ fi
 # ----------------------------------------
 # Extra
 # ----------------------------------------
-
-# What compiler are we using ?
-if test x$GXX != xyes ; then
-  { echo "$as_me:6342: WARNING: g++ is the recommended compiler: expect trouble." >&5
-echo "$as_me: WARNING: g++ is the recommended compiler: expect trouble." >&2;}
-  if test $ac_cv_cxx_exceptions = no ; then
-    { { echo "$as_me:6345: error: exception support in c++ compiler is mandatory." >&5
-echo "$as_me: error: exception support in c++ compiler is mandatory." >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-else
-  case "`$CXX --version`" in
-    *2.95.*) ;;
-    *2.96*) ;;
-    *3.*) ;;
-    *2.91.*) { echo "$as_me:6354: WARNING: strongly suggesting g++ 2.95.3 or better" >&5
-echo "$as_me: WARNING: strongly suggesting g++ 2.95.3 or better" >&2;} ;;
-    *) { { echo "$as_me:6356: error: use a better compiler such as g++ 2.95.3 or better" >&5
-echo "$as_me: error: use a better compiler such as g++ 2.95.3 or better" >&2;}
-   { (exit 1); exit 1; }; } ;;
-  esac
-fi
-
-# What version of QT are we using
-if test x${qt_version+set} = xset ; then
-  if test "$qt_version" -lt 220 ; then
-     { echo "$as_me:6365: WARNING: We suggest using QT-2.2.0 or better." >&5
-echo "$as_me: WARNING: We suggest using QT-2.2.0 or better." >&2;}
-  elif test "$qt_version" -ge 300 ; then
-     { echo "$as_me:6368: WARNING: We do not yet support QT-3.x." >&5
-echo "$as_me: WARNING: We do not yet support QT-3.x." >&2;}
-  fi
-fi
-
-# Rules for building the netscape plugin.
-NSDEJAVU='nsdejavu.so'
-NSDEJAVU_FLAGS='-fpic -DPIC'
-NSDEJAVU_LIBS="-lXt -lX11"
-test -n "$x_libraries" && NSDEJAVU_LIBS="-L$x_libraries $NSDEJAVU_LIBS"
-NSDEJAVU_LINK='${CC} -shared -o ${NSDEJAVU} ${CFLAGS} -shared ${OBJS} ${LIBS}'
-case ${host_os} in
-  hpux*) NSDEJAVU="nsdejavu.sl" ;;
-esac
-if test x${GXX} != xyes ; then
-    { echo "$as_me:6383: WARNING: Check that gui/nsdejavu/Makefile works with this compiler." >&5
-echo "$as_me: WARNING: Check that gui/nsdejavu/Makefile works with this compiler." >&2;}
-fi
 
 # Should libdjvu be a shared library ?
 ac_shared_libdjvu=no
@@ -6406,17 +6363,64 @@ fi
 
 # Work around broken compilers with the famous LPR0 bug
 if test x$ac_shared_libdjvu != xno && test x$GXX = xyes; then
-    echo "$as_me:6409: checking if $CXX has the LPR0 bug" >&5
+    echo "$as_me:6366: checking if $CXX has the LPR0 bug" >&5
 echo $ECHO_N "checking if $CXX has the LPR0 bug... $ECHO_C" >&6
     echo 'extern "C" { inline int sqr(int x) throw() { return x * x ; } } int main() {} ' > conftest.cc
     if ${CXX} -fPIC ${OPTS} conftest.cc -o conftest >/dev/null 2>/dev/null ; then
-        echo "$as_me:6413: result: no" >&5
+        echo "$as_me:6370: result: no" >&5
 echo "${ECHO_T}no" >&6
     else
-        echo "$as_me:6416: result: yes" >&5
+        echo "$as_me:6373: result: yes" >&5
 echo "${ECHO_T}yes" >&6
         OPTS=`echo $OPTS | sed -e 's/-mcpu=i686/-mpentium/'`
     fi
+fi
+
+# What compiler are we using ?
+if test x$GXX != xyes ; then
+  { echo "$as_me:6381: WARNING: g++ is the recommended compiler: expect trouble." >&5
+echo "$as_me: WARNING: g++ is the recommended compiler: expect trouble." >&2;}
+  if test $ac_cv_cxx_exceptions = no ; then
+    { { echo "$as_me:6384: error: exception support in c++ compiler is mandatory." >&5
+echo "$as_me: error: exception support in c++ compiler is mandatory." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+else
+  case "`$CXX --version`" in
+    *2.95.*) ;;
+    *2.96*) ;;
+    *3.*) ;;
+    *2.91.*) { echo "$as_me:6393: WARNING: strongly suggesting g++ 2.95.3 or better" >&5
+echo "$as_me: WARNING: strongly suggesting g++ 2.95.3 or better" >&2;} ;;
+    *) { { echo "$as_me:6395: error: use a better compiler such as g++ 2.95.3 or better" >&5
+echo "$as_me: error: use a better compiler such as g++ 2.95.3 or better" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
+fi
+
+# What version of QT are we using
+if test x${qt_version+set} = xset ; then
+  if test "$qt_version" -lt 220 ; then
+     { echo "$as_me:6404: WARNING: We suggest using QT-2.2.0 or better." >&5
+echo "$as_me: WARNING: We suggest using QT-2.2.0 or better." >&2;}
+  elif test "$qt_version" -ge 300 ; then
+     { echo "$as_me:6407: WARNING: We do not yet support QT-3.x." >&5
+echo "$as_me: WARNING: We do not yet support QT-3.x." >&2;}
+  fi
+fi
+
+# Rules for building the netscape plugin.
+NSDEJAVU='nsdejavu.so'
+NSDEJAVU_FLAGS='-fpic -DPIC'
+NSDEJAVU_LIBS="-lXt -lX11"
+test -n "$x_libraries" && NSDEJAVU_LIBS="-L$x_libraries $NSDEJAVU_LIBS"
+NSDEJAVU_LINK='${CC} -shared -o ${NSDEJAVU} ${CFLAGS} -shared ${OBJS} ${LIBS}'
+case ${host_os} in
+  hpux*) NSDEJAVU="nsdejavu.sl" ;;
+esac
+if test x${GXX} != xyes ; then
+    { echo "$as_me:6422: WARNING: Please verify that gui/nsdejavu/Makefile works with this compiler." >&5
+echo "$as_me: WARNING: Please verify that gui/nsdejavu/Makefile works with this compiler." >&2;}
 fi
 
 # ----------------------------------------
@@ -6562,7 +6566,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6565: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6569: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -6734,7 +6738,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:6737: error: ambiguous option: $1
+    { { echo "$as_me:6741: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6753,7 +6757,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:6756: error: unrecognized option: $1
+  -*) { { echo "$as_me:6760: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6796,7 +6800,7 @@ do
   "gui/djview/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/djview/Makefile" ;;
   "gui/nsdejavu/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/nsdejavu/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config/config.h.in" ;;
-  *) { { echo "$as_me:6799: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:6803: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -6925,12 +6929,12 @@ s,@MOC@,$MOC,;t t
 s,@UIC@,$UIC,;t t
 s,@GUI_YES@,$GUI_YES,;t t
 s,@GUI_NO@,$GUI_NO,;t t
+s,@SHARED_YES@,$SHARED_YES,;t t
+s,@SHARED_NO@,$SHARED_NO,;t t
 s,@NSDEJAVU@,$NSDEJAVU,;t t
 s,@NSDEJAVU_FLAGS@,$NSDEJAVU_FLAGS,;t t
 s,@NSDEJAVU_LIBS@,$NSDEJAVU_LIBS,;t t
 s,@NSDEJAVU_LINK@,$NSDEJAVU_LINK,;t t
-s,@SHARED_YES@,$SHARED_YES,;t t
-s,@SHARED_NO@,$SHARED_NO,;t t
 CEOF
 
 EOF
@@ -7040,7 +7044,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7043: creating $ac_file" >&5
+    { echo "$as_me:7047: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7058,7 +7062,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7061: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7065: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7071,7 +7075,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7074: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7078: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7131,7 +7135,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7134: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7138: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7142,7 +7146,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7145: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7149: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7155,7 +7159,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7158: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7162: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7272,7 +7276,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7275: $ac_file is unchanged" >&5
+      { echo "$as_me:7279: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
