Imported i18n changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SET_MAKE RANLIB ac_ct_RANLIB LN_S RM AR TOUCH INSTALL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX OPTS CXXRPOFLAGS RPO_YES RPO_NO CXXCPP EGREP JPEG_LIBS JPEG_CFLAGS PTHREAD_LIBS PTHREAD_CFLAGS THREAD_LIBS THREAD_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QT_CFLAGS QT_LIBS MOC UIC XML_YES XML_NO GUI_YES GUI_NO SHARED_YES SHARED_NO NSDEJAVU NSDEJAVU_FLAGS NSDEJAVU_LIBS NSDEJAVU_LINK LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os SET_MAKE RANLIB ac_ct_RANLIB LN_S RM AR TOUCH MKDIR INSTALL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX OPTS CXXRPOFLAGS RPO_YES RPO_NO CXXCPP EGREP JPEG_LIBS JPEG_CFLAGS PTHREAD_LIBS PTHREAD_CFLAGS THREAD_LIBS THREAD_CFLAGS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QT_CFLAGS QT_LIBS MOC UIC LUPDATE LRELEASE XML_YES XML_NO GUI_YES GUI_NO SHARED_YES SHARED_NO NSDEJAVU NSDEJAVU_FLAGS NSDEJAVU_LIBS NSDEJAVU_LINK LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1671,6 +1671,45 @@ TOUCH=$ac_cv_path_TOUCH
 if test -n "$TOUCH"; then
   echo "$as_me:$LINENO: result: $TOUCH" >&5
 echo "${ECHO_T}$TOUCH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "mkdir", so it can be a program name with args.
+set dummy mkdir; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_MKDIR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MKDIR in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MKDIR="$MKDIR" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_MKDIR="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+MKDIR=$ac_cv_path_MKDIR
+
+if test -n "$MKDIR"; then
+  echo "$as_me:$LINENO: result: $MKDIR" >&5
+echo "${ECHO_T}$MKDIR" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -8130,7 +8169,7 @@ fi
 
   test -n "$MOC" && break
 done
-test -n "$MOC" || MOC="unknown"
+test -n "$MOC" || MOC=":"
 
     for ac_prog in uic uic3 uic2
 do
@@ -8175,11 +8214,101 @@ fi
 
   test -n "$UIC" && break
 done
-test -n "$UIC" || UIC="unknown"
+test -n "$UIC" || UIC=":"
+
+    for ac_prog in lupdate
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_LUPDATE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LUPDATE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LUPDATE="$LUPDATE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $QTDIR/bin $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_LUPDATE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+LUPDATE=$ac_cv_path_LUPDATE
+
+if test -n "$LUPDATE"; then
+  echo "$as_me:$LINENO: result: $LUPDATE" >&5
+echo "${ECHO_T}$LUPDATE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$LUPDATE" && break
+done
+test -n "$LUPDATE" || LUPDATE=":"
+
+    for ac_prog in lrelease
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_LRELEASE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LRELEASE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LRELEASE="$LRELEASE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $QTDIR/bin $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_LRELEASE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+LRELEASE=$ac_cv_path_LRELEASE
+
+if test -n "$LRELEASE"; then
+  echo "$as_me:$LINENO: result: $LRELEASE" >&5
+echo "${ECHO_T}$LRELEASE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$LRELEASE" && break
+done
+test -n "$LRELEASE" || LRELEASE=":"
 
     if test -x "$MOC" ; then : ; else
-        { echo "$as_me:$LINENO: WARNING: Cannot run the Qt Meta-Object compiler." >&5
-echo "$as_me: WARNING: Cannot run the Qt Meta-Object compiler." >&2;}
+        { echo "$as_me:$LINENO: WARNING: Cannot locate the Qt Meta-Object compiler." >&5
+echo "$as_me: WARNING: Cannot locate the Qt Meta-Object compiler." >&2;}
         ac_has_qt=no
         QTDIR=no
     fi
@@ -9203,6 +9332,7 @@ s,@LN_S@,$LN_S,;t t
 s,@RM@,$RM,;t t
 s,@AR@,$AR,;t t
 s,@TOUCH@,$TOUCH,;t t
+s,@MKDIR@,$MKDIR,;t t
 s,@INSTALL@,$INSTALL,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
@@ -9235,6 +9365,8 @@ s,@QT_CFLAGS@,$QT_CFLAGS,;t t
 s,@QT_LIBS@,$QT_LIBS,;t t
 s,@MOC@,$MOC,;t t
 s,@UIC@,$UIC,;t t
+s,@LUPDATE@,$LUPDATE,;t t
+s,@LRELEASE@,$LRELEASE,;t t
 s,@XML_YES@,$XML_YES,;t t
 s,@XML_NO@,$XML_NO,;t t
 s,@GUI_YES@,$GUI_YES,;t t
