Prepare release 3.5.3. Added version info in config.h. Added version info in all command line tools.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.ac Id: configure.ac.
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for djvu 3.5.
+# Generated by Autoconf 2.52 for djvulibre 3.5.3.
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 # Free Software Foundation, Inc.
@@ -183,10 +183,10 @@ infodir='${prefix}/info'
 mandir='${prefix}/man'
 
 # Identity of this package.
-PACKAGE_NAME='djvu'
-PACKAGE_TARNAME='djvu'
-PACKAGE_VERSION='3.5'
-PACKAGE_STRING='djvu 3.5'
+PACKAGE_NAME='djvulibre'
+PACKAGE_TARNAME='djvulibre'
+PACKAGE_VERSION='3.5.3'
+PACKAGE_STRING='djvulibre 3.5.3'
 PACKAGE_BUGREPORT=''
 
 ac_prev=
@@ -647,7 +647,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures djvu 3.5 to adapt to many kinds of systems.
+\`configure' configures djvulibre 3.5.3 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -712,7 +712,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of djvu 3.5:";;
+     short | recursive ) echo "Configuration of djvulibre 3.5.3:";;
    esac
   cat <<\EOF
 
@@ -799,7 +799,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-djvu configure 3.5
+djvulibre configure 3.5.3
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -814,7 +814,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by djvu $as_me 3.5, which was
+It was created by djvulibre $as_me 3.5.3, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -6532,7 +6532,7 @@ fi
 # End
 # ----------------------------------------
 
-# Define installation paths
+# Define installation paths and version string
 
   save_prefix="${prefix}"
   save_exec_prefix="${exec_prefix}"
@@ -6576,6 +6576,10 @@ EOF
 
   prefix="${save_prefix}"
   exec_prefix="${save_exec_prefix}"
+
+cat >>confdefs.h <<EOF
+#define DJVULIBRE_VERSION "${PACKAGE_VERSION}"
+EOF
 
 # Output files
 ac_config_files="$ac_config_files Makefile"
@@ -6671,7 +6675,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6674: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6678: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -6799,7 +6803,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-djvu config.status 3.5
+djvulibre config.status 3.5.3
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -6843,7 +6847,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:6846: error: ambiguous option: $1
+    { { echo "$as_me:6850: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6862,7 +6866,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:6865: error: unrecognized option: $1
+  -*) { { echo "$as_me:6869: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -6881,7 +6885,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (djvu 3.5) 2.52, executed with
+This file was extended by $as_me (djvulibre 3.5.3) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -6905,7 +6909,7 @@ do
   "gui/djview/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/djview/Makefile" ;;
   "gui/nsdejavu/Makefile" ) CONFIG_FILES="$CONFIG_FILES gui/nsdejavu/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config/config.h.in" ;;
-  *) { { echo "$as_me:6908: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:6912: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7149,7 +7153,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7152: creating $ac_file" >&5
+    { echo "$as_me:7156: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7167,7 +7171,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7170: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7174: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7180,7 +7184,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7183: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7187: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7240,7 +7244,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7243: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7247: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7251,7 +7255,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7254: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7258: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7264,7 +7268,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7267: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7271: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7381,7 +7385,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7384: $ac_file is unchanged" >&5
+      { echo "$as_me:7388: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
